<?php

namespace ContainerX1WfQl5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronJobControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CronJobController' shared autowired service.
     *
     * @return \App\Controller\CronJobController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CronJobController.php';

        $container->services['App\\Controller\\CronJobController'] = $instance = new \App\Controller\CronJobController(($container->privates['App\\Service\\CrontabManager\\CrontabManagerInterface'] ?? $container->load('getCrontabManagerInterfaceService')), $container->getEnv('default:app.default_crontab_user:DEFAULT_CRONTAB_USER'));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CronJobController', $container));

        return $instance;
    }
}
