<?php

namespace ContainerX1WfQl5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCronJobTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CronJobType' shared autowired service.
     *
     * @return \App\Form\CronJobType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CronJobType.php';

        return $container->privates['App\\Form\\CronJobType'] = new \App\Form\CronJobType($container->getEnv('default:app.default_crontab_user:DEFAULT_CRONTAB_USER'));
    }
}
