<?php

namespace ContainerX1WfQl5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListJobsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\ListJobsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\ListJobsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:cron:list', [], 'List all cron jobs', false, #[\Closure(name: 'App\\Command\\ListJobsCommand')] fn (): \App\Command\ListJobsCommand => ($container->privates['App\\Command\\ListJobsCommand'] ?? $container->load('getListJobsCommandService')));
    }
}
