<?php

namespace ContainerX1WfQl5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListJobsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ListJobsCommand' shared autowired service.
     *
     * @return \App\Command\ListJobsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ListJobsCommand.php';

        $container->privates['App\\Command\\ListJobsCommand'] = $instance = new \App\Command\ListJobsCommand(($container->privates['App\\Service\\CrontabManager\\CrontabManagerInterface'] ?? $container->load('getCrontabManagerInterfaceService')));

        $instance->setName('app:cron:list');
        $instance->setDescription('List all cron jobs');

        return $instance;
    }
}
