<?php

namespace ContainerX1WfQl5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatformHandlerInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Platform\PlatformHandlerInterface' shared autowired service.
     *
     * @return \App\Service\Platform\StandardPlatformHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Platform/PlatformHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Platform/StandardPlatformHandler.php';

        return $container->privates['App\\Service\\Platform\\PlatformHandlerInterface'] = new \App\Service\Platform\StandardPlatformHandler('cron', ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
